module.exports = Object.freeze({
  NOT_FOUND: 'Record not found',
  EXIST: 'Record exist',
  GONE_BAD: 'Sorry! something went wrong, we are working on it',
  SUCCESS: 'Request Processed Successfully',
  FAILED: 'Request Processing Failed',
  EMPTY_PAYLOAD: 'Payload Is Empty',
  DUPLICATE_USER:
    'Hey we seem to have your records, kindly login with your email or phone number',
  INVALID_USER: 'Invalid User Credentials',
  TOKEN_RANGE: 10000,
  TOKEN_SENT: 'Token Sent, Check your email or SMS inbox',
  ACCOUNT_NOT_ACTIVATED: 'Account Is Not Activated',
  INVALID_TOKEN: 'Invalid Details or this account has been activated',
  ACCOUNT_TYPE_MARKETER: 'Marketer',
  PROVIDER_PROVIDUS: 'Providus',
  PROVIDER_KUDA: 'Kuda',
  INVALID_PIN: 'Invalid Pin',
  WITHDRAWAL_ACCOUNT: 'Withdrawal',
  TRANSFER_JOB: 'TRANSFER_JOB',
  USER_ACCOUNT: 'User',
  MERCHANT_ACCOUNT: 'Merchant',
  BULK_TRANSFER_JOB: 'BULK TRANSFER JOB',
  CHARGES: {
    DATA: 'DATA',
    MTN_AIRTIME: 'MTN AIRTIME',
    AIRTEL_AIRTIME: 'AIRTEL AIRTIME',
    GLO_AIRTIME: 'GLO AIRTIME',
    m_9MOBILE_AIRTIME: '9MOBILE AIRTIME',
    TRANSFER: 'Transfer',
    TV_SUBSCRIPTION: 'TV-SUBSCRIPTION',
    ELECTRICITY: 'ELECTRICITY',
    AIRTIME: 'AIRTIME',
  },
  TRANSACTION_TYPE: {
    EXPENSE: 'EXPENSE',
    INCOME: 'INCOME',
  },
  TRANSACTION_STATUS: {
    PAID: 'PAID',
    PENDING: 'PENDING',
  },
  STATUS: {
    REVERSED: 'REVERSED',
    FAILED: 'FAILED',
  },
});
